version: '2'
services:
  WeatherService:
    build: ./WeatherService
    image: tautvis/weatherservice
    working_dir: /WeatherService
    volumes:
      - ./WeatherService:/WeatherService
      - ~/.m2:/root/.m2
    ports:
      - "5000:5000"
    command: bash -c "mvn clean package && java -jar target/oru-servisas-jar-with-dependencies.jar"

  app:
    build: ./Service
    image: tautvis/service
    working_dir: /Service
    volumes:
      - ./Service:/Service
      - ~/.m2:/root/.m2
    ports:
      - "80:80"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WebServicesPostsService
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    container_name: mysql-standalone
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql