//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 03:45:13 PM EEST 
//


package com.userspostscomments.posts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdPost" type="{http://usersPostsComments.com/posts}post"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createdPost"
})
@XmlRootElement(name = "createPostResponse")
public class CreatePostResponse {

    @XmlElement(required = true)
    protected Post createdPost;

    /**
     * Gets the value of the createdPost property.
     * 
     * @return
     *     possible object is
     *     {@link Post }
     *     
     */
    public Post getCreatedPost() {
        return createdPost;
    }

    /**
     * Sets the value of the createdPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Post }
     *     
     */
    public void setCreatedPost(Post value) {
        this.createdPost = value;
    }

}
