//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 03:45:13 PM EEST 
//


package com.userspostscomments.posts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.userspostscomments.posts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.userspostscomments.posts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreatePostRequest }
     * 
     */
    public CreatePostRequest createCreatePostRequest() {
        return new CreatePostRequest();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link UpdatePostResponse }
     * 
     */
    public UpdatePostResponse createUpdatePostResponse() {
        return new UpdatePostResponse();
    }

    /**
     * Create an instance of {@link Post }
     * 
     */
    public Post createPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link GetAllPostsResponse }
     * 
     */
    public GetAllPostsResponse createGetAllPostsResponse() {
        return new GetAllPostsResponse();
    }

    /**
     * Create an instance of {@link CreatePostResponse }
     * 
     */
    public CreatePostResponse createCreatePostResponse() {
        return new CreatePostResponse();
    }

    /**
     * Create an instance of {@link UpdatePostRequest }
     * 
     */
    public UpdatePostRequest createUpdatePostRequest() {
        return new UpdatePostRequest();
    }

    /**
     * Create an instance of {@link GetPostByIdRequest }
     * 
     */
    public GetPostByIdRequest createGetPostByIdRequest() {
        return new GetPostByIdRequest();
    }

    /**
     * Create an instance of {@link DeletePostResponse }
     * 
     */
    public DeletePostResponse createDeletePostResponse() {
        return new DeletePostResponse();
    }

    /**
     * Create an instance of {@link GetPostByIdResponse }
     * 
     */
    public GetPostByIdResponse createGetPostByIdResponse() {
        return new GetPostByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllPostsRequest }
     * 
     */
    public GetAllPostsRequest createGetAllPostsRequest() {
        return new GetAllPostsRequest();
    }

    /**
     * Create an instance of {@link DeletePostRequest }
     * 
     */
    public DeletePostRequest createDeletePostRequest() {
        return new DeletePostRequest();
    }

}
