//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 08:04:53 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://usersPostsComments.com/posts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.userspostscomments.posts;
