//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 08:04:53 PM EEST 
//


package com.userspostscomments.comments;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.userspostscomments.comments package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.userspostscomments.comments
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteCommentRequest }
     * 
     */
    public DeleteCommentRequest createDeleteCommentRequest() {
        return new DeleteCommentRequest();
    }

    /**
     * Create an instance of {@link GetAllCommentsRequest }
     * 
     */
    public GetAllCommentsRequest createGetAllCommentsRequest() {
        return new GetAllCommentsRequest();
    }

    /**
     * Create an instance of {@link CreateCommentRequest }
     * 
     */
    public CreateCommentRequest createCreateCommentRequest() {
        return new CreateCommentRequest();
    }

    /**
     * Create an instance of {@link UpdateCommentResponse }
     * 
     */
    public UpdateCommentResponse createUpdateCommentResponse() {
        return new UpdateCommentResponse();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link CreateCommentResponse }
     * 
     */
    public CreateCommentResponse createCreateCommentResponse() {
        return new CreateCommentResponse();
    }

    /**
     * Create an instance of {@link DeleteCommentResponse }
     * 
     */
    public DeleteCommentResponse createDeleteCommentResponse() {
        return new DeleteCommentResponse();
    }

    /**
     * Create an instance of {@link GetCommentByIdRequest }
     * 
     */
    public GetCommentByIdRequest createGetCommentByIdRequest() {
        return new GetCommentByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateCommentRequest }
     * 
     */
    public UpdateCommentRequest createUpdateCommentRequest() {
        return new UpdateCommentRequest();
    }

    /**
     * Create an instance of {@link GetAllCommentsResponse }
     * 
     */
    public GetAllCommentsResponse createGetAllCommentsResponse() {
        return new GetAllCommentsResponse();
    }

    /**
     * Create an instance of {@link GetCommentByIdResponse }
     * 
     */
    public GetCommentByIdResponse createGetCommentByIdResponse() {
        return new GetCommentByIdResponse();
    }

}
